### ISSUE TITLE
Scrollbar on the right broken

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/software.acellera.com#12] opened 2018-01-16 21:29 UTC
It is longer than the page? Is this a good explanation?

https://software.acellera.com/docs/latest/htmd/tutorials/getting-started-with-htmd.html

Both on firefox and chrome

**Comment by alejandrovr** [comment] 2018-01-16 21:42
Ok, I will look into it. Thanks for pointing it out.

**Comment by alejandrovr** [comment] 2018-01-17 09:37
This issue was caused by the fix for the navbar scroll problem. The new version (already pushed) reverts that fix until we have another solution. Until now, only adding one more scrollbar on the right seems to be able to make it work properly, but it is not very nice.

**Comment by j3mdamas** [comment] 2018-01-17 12:30
So, we publish that one, close this issue and reopen the other one?

**Comment by alejandrovr** [comment] 2018-01-17 12:40
Yes, publish my latest push, close this one and reopen the other.

**Closed** 2018-01-17 13:13 UTC
Labels: bug
